//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book: Item
    {
        public int BookId { get; set; }
        
        public string Publisher { get; set; }
        public string Author { get; set; }
        public string Genre { get; set; }
        public Nullable<int> IssuedTo { get; set; }

        public delegate void BookBorrowedEventHandler(object sender, EventArgs e);

        // Define the event based on the delegate
        public event BookBorrowedEventHandler BookBorrowed;
        public override bool Borrow() // hiding
        {
            if (IssuedTo == null)
                return true;
            return false;
        }
        public virtual void OnBookBorrowed()
        {
            // Check if there are any subscribers to the event
            if (BookBorrowed != null)
            {
                // Raise the event
                BookBorrowed(this, EventArgs.Empty);
            }
        }

        public virtual User User { get; set; }
    }
}
