//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibrarySystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Magazine: Item
    {
        public int MagazineId { get; set; }
        //public string Name { get; set; }
        public string Publisher { get; set; }
        public string Brand { get; set; }
        public Nullable<int> IssuedTo { get; set; }
        public override bool Borrow() // hiding
        {
            if (IssuedTo == null)
                return true;
            return false;
        }

        public virtual User User { get; set; }
    }
}
